services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pizza
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data